spring:
  application:
    name: PRODUCT-SERVICE
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  datasource:
    username: sa
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    password: Hello
  jpa:
    database-open-in-view: 'false'
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl:
        auto: create
server:
  port: '8081'


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:HTTP://localhost:8761/eureka}